### ISSUE TITLE
BankNote's constructors look weird.

### ISSUE THREAD

**Issue by taveratch** [OOP2018/coinpurse-PittayutSothanakul#10]
First, any constructor should increase serialNumber and assign to BankNote automatically.
Second, the second constructor accepts serialNumber as param but does not use it.

https://github.com/OOP2018/coinpurse-PittayutSothanakul/blob/6cdde1be3f1cfb91891ae3eb32b5ef1481066633/src/coinpurse/BankNote.java#L15-L35

**Comment by PittayutSothanakul** [comment]
I modify already.
