### ISSUE TITLE
withdraw() does not check for the currency.

### ISSUE THREAD

**Issue by taveratch** [OOP2018/coinpurse-PittayutSothanakul#16]

**Comment by PittayutSothanakul** [comment]
I check currency in withdraw() already.

**Comment by taveratch** [comment]
It's still wrong. Purse should be able to check with the same currency as the argument.

**Comment by PittayutSothanakul** [comment]
Ok I checked money.get(i).getCurrency().equalsIgnoreCase(amount.getCurrency())
