### ISSUE TITLE
Useless code in getBalance()

### ISSUE THREAD

**Issue by bokherus** [OOP2018/coinpurse-PittayutSothanakul#2]
1. If you plan to have an attribute for balance in Purse then don't compute the balance every time the method is called, and just return the attribute balance. But you should find a way to update the balance in the purse if you would like to keep balance as an attribute.
2. Just compute the balance and return it no need to store it as an attribute.

**Comment by PittayutSothanakul** [comment]
I change return this.balance; --> return balance; .
