### ISSUE TITLE
Incorrect Exception handling

### ISSUE THREAD

**Issue by kykungz** [OOP2018/coinpurse-PittayutSothanakul#20]
MoneyFactory `createMoney` should throw `IllegalArgumentException` not catching them.

`Double.parseDouble()` javadoc said it would throw `NumberFormatException` if it fails.
Catching `IllegalArgumentException e` is not appropriate here (even though `NumberFormatException` do **extends** `IllegalArgumentException`).

Consider catching `NumberFormatException e` or `Exception e`

After catching, you should transform the exception into `IllegalArgumentException` with messages. By `throw new IllegalArgumentException("error message", e);`

**Comment by PittayutSothanakul** [comment]
catch NumberFormatException instead IllegalArgumentException
and put messages in IllegalArgumentException already.

**Comment by kykungz** [comment]
You should also pass the `e` to your `IllegalArgumentException`

```java
// Your code
} catch (NumberFormatException e) {
      throw new IllegalArgumentException(value = "cann't parse to double");
}
```

**Comment by PittayutSothanakul** [comment]
I pass the e to my IllegalArgumentException already.
