### ISSUE TITLE
BankNote still generate its own serialNumber

### ISSUE THREAD

**Issue by kykungz** [OOP2018/coinpurse-PittayutSothanakul#23]
The point of using `MoneyFactory` is to make `MoneyFactory` keep track of the `serialNumber`, so the `BankNote` will be just a "model" of bank notes, which should not know about others serialNumber. The `serialNumber` should be assigned by the `MoneyFactory`

**Comment by PittayutSothanakul** [comment]
BankNote still generate its own serialNumber already.
