### ISSUE TITLE
What kind of String Comparison is this?

### ISSUE THREAD

**Issue by taveratch** [OOP2018/coinpurse-PittayutSothanakul#9]
https://github.com/OOP2018/coinpurse-PittayutSothanakul/blob/1b65880f377e82802046e155dc942196c909a405/src/coinpurse/Coin.java#L55

Check BankNote too.

**Comment by PittayutSothanakul** [comment]
I check BankNote already.

**Comment by taveratch** [comment]
You should use equals() instead of == for String comparison because using == may cause bugs in your code.

**Comment by PittayutSothanakul** [comment]
Ok I use .equal() already
